package vo;
// Generated 18/10/2019 23:06:00 by Hibernate Tools 4.3.1



/**
 * Expressao generated by hbm2java
 */
public class Expressao  implements java.io.Serializable {


     private ExpressaoId id;
     private Palavra palavra;
     private String expressao;

    public Expressao() {
    }

	
    public Expressao(ExpressaoId id, Palavra palavra) {
        this.id = id;
        this.palavra = palavra;
    }
    public Expressao(ExpressaoId id, Palavra palavra, String expressao) {
       this.id = id;
       this.palavra = palavra;
       this.expressao = expressao;
    }
   
    public ExpressaoId getId() {
        return this.id;
    }
    
    public void setId(ExpressaoId id) {
        this.id = id;
    }
    public Palavra getPalavra() {
        return this.palavra;
    }
    
    public void setPalavra(Palavra palavra) {
        this.palavra = palavra;
    }
    public String getExpressao() {
        return this.expressao;
    }
    
    public void setExpressao(String expressao) {
        this.expressao = expressao;
    }




}


