package vo;
// Generated 18/10/2019 23:06:00 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Palavra generated by hbm2java
 */
public class Palavra implements java.io.Serializable {

    private Integer id;
    private String palavra;
    private Set expressao = new HashSet(0);

    public Palavra() {
    }

    public Palavra(String palavra, Set expressao) {
        this.palavra = palavra;
        this.expressao = expressao;
    }

    public Palavra(int id, String palavra, Set expressao) {
        this.palavra = palavra;
        this.expressao = expressao;
        this.id = id;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getPalavra() {
        return this.palavra;
    }

    public void setPalavra(String palavra) {
        this.palavra = palavra;
    }

    public Set getExpressao() {
        return this.expressao;
    }

    public void setExpressao(Set expressao) {
        this.expressao = expressao;
    }

}
